### ISSUE TITLE
Missmatch RasPi Pin to GPIO assignment

### ISSUE THREAD

**Issue by Makkus81739** [eenemeenemuu/hoymiles_zero_export#1]
Connecting the NR24F: the IRQ is connected to Pi pin 16 GPIO 12. But looking at the Pi header layout (RasPi 2 B) GPIO 12 is either on pin 32 or pin 16 matches to GPIO 23. IMHO the combination GPIO 12 on pin 32 is corrected. This should be reflected in the md file. :-)

**Comment by eenemeenemuu** [comment]
I'm using a Raspberry Pi 1B, pin 32 doesn't exist here (maybe it was a typo of GPIO12 vs. GPIO23). However, IRQ does not seem to be needed at all. I have just disconnected it and everything still works.

I have updated the docs accordingly, thank you.

**Comment by Makkus81739** [comment]
I recently found an article about the IRQ line and it sayed that even though it works w/o it, it is recommended to use it to reduce CPU load on the RasPi...
